

const PrivacyAndPolicy = () => {
  return (
    <section className="mt-10 md:px-12 px-4">
      <h1 className="md:text-3xl text-2xl">Privacy and Policy</h1>
      <div className="h-2 w-14 bg-secondary" />
      <article className="space-y-8 mt-4 text-sm">
        <p>This page informs you of our policies regarding the collection, use and disclosure of personal data when you use our Service and the choices you have associated with that data. We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions. Definitions</p>
        <p>Personal Data: Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
        <p>Usage Data: <br />
          Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
        <p>Information Collection and Use:</p>
        <p>We collect several different types of information for various purposes to provide and improve our Service to you. Types of Data Collected Personal Data While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (&quot;Personal Data&quot;). Personally identifiable information may include, but is not limited to: <br />
          Email address <br />
          First name and last name <br />
          Phone number <br />
          Address, State, Province, ZIP/Postal code, City <br />
          Cookies and Usage Data</p>
        <p>Usage Data: We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device (&quot;Usage Data&quot;). This Usage Data may include information such as your computer&4qf89tvc;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data. When you access the Service with a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data. Location Data</p>
        <p>We may use and store information about your location if you give us permission to do so (&apos;Location Data&apos;). We use this data to provide features of our Service, to improve and customize our Service. You can enable or disable location services when you use our Service at any time by way of your device settings.</p>
        <p>Tracking & Cookies Data: We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information. Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyses our Service. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service. Examples of Cookies we use:
          Session Cookies. We use Session Cookies to operate our Service.
          Preference Cookies. We use Preference Cookies to remember your preferences and various settings.
          Security Cookies. We use Security Cookies for security purposes.</p>
        <p>Use of Data:</p>
        <p>WIDEPAYCASH uses the collected data for various purposes:<br />
          To provide and maintain our Service<br />
          To notify you about changes to our Service<br />
          To allow you to participate in interactive features of our Service when you choose to do so<br />
          To provide customer support<br />
          To gather analysis or valuable information so that we can improve our Service<br />
          To monitor the usage of our Service<br />
          To detect, prevent and address technical issues</p>
        <p>Transfer of Data: Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction. If you are located outside Ghana and choose to provide information to us, please note that we transfer the data, including Personal Data, to Ghana and process it there. Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer. WIDEPAYCASH will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information. Disclosure of Data Disclosure for Law Enforcement Under certain circumstances, WIDEPAYCASH may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency). Legal Requirements WIDEPAYCASH may disclose your Personal Data in the good faith belief that such action is necessary to: To comply with a legal obligation</p>
        <p>To protect and defend the rights or property of WIDEPAYCASH To prevent or investigate possible wrongdoing in connection with the Service<br />
          To protect the personal safety of users of the Service or the public<br />
          To protect against legal liability</p>
        <p>Security of Data: The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security. Service Providers We may employ third party companies and individuals to facilitate our Service (&apos;Service Providers&apos;), provide the Service on our behalf, perform Service-related services or assist us in analyzing how our Service is used. These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>
        <p>Links to Other Sites: Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party&quot;s site. We strongly advise you to review the Privacy Policy of every site you visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
        <p>Children&quot;s Privacy: Our Service does not address anyone under the age of 18 (&quot;Children&quot;). We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</p>
        <p>Changes to This Privacy Policy: We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the &quot;effective date&quot; at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
      </article>
    </section>
  )
}

export default PrivacyAndPolicy
